# Generated by Django 3.2.12 on 2022-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20220324_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='map_url',
            field=models.CharField(default='https://www.google.com/maps?q=<django.db.models.fields.CharField>+<django.db.models.fields.CharField>&output=embed', max_length=150),
        ),
    ]
